Restart containerd after injecting config_path config to containerd config file
dragonflyoss/helm-charts pull request #122
Opened 2022-10-09 09:05 UTC by Leo-Song

2022-10-09 09:47 UTC, Leo-Song commented
related issue https://github.com/dragonflyoss/helm-charts/issues/120

2022-10-10 04:17 UTC, gaius-qi approved these changes
LGTM

2022-10-10 04:17 UTC, gaius-qi requested changes
Update charts version.

2022-10-10 07:50 UTC, gaius-qi approved these changes
LGTM

2022-10-10 07:50 UTC, merged