add chart for nydus-snapshotter
dragonflyoss/helm-charts pull request #131
Opened 2022-11-23 03:58 UTC by liubin

Add new chart for nydus-snapshotter includes:

- daemonset for running nydus-snapshotter inside containers
- a configmap for configuring nydus-snapshotter

Signed-off-by: bin liu <liubin0329@gmail.com>

2022-11-28 03:12 UTC, gaius-qi requested changes

2022-11-28 03:12 UTC, gaius-qi commented on charts/nydus-snapshotter/values.yaml
> +nydusSnapshotter:
`nydusSnapshotter` should be removed as there is only one nydusSnapshotter service, refer to https://github.com/bitnami/charts.

2022-11-28 03:12 UTC, gaius-qi commented on charts/nydus-snapshotter/values.yaml
> +  name: nydus-snapshotter
`name` should be removed as there is only one nydusSnapshotter service, refer to https://github.com/bitnami/charts.

2022-11-28 03:12 UTC, gaius-qi commented on charts/nydus-snapshotter/values.yaml
> +  nameOverride: ""
`nameOverride` should be removed as there is only one nydusSnapshotter service, refer to https://github.com/bitnami/charts.

2022-11-28 03:12 UTC, gaius-qi commented on charts/nydus-snapshotter/values.yaml
> +  fullnameOverride: ""
`fullnameOverride` should be removed as there is only one nydusSnapshotter service, refer to https://github.com/bitnami/charts.

2022-12-05 14:25 UTC, nextauthn commented
Nydus snapshotter doesn't share private registries creds with containerd.  Instead, this supports authentication in the following methods,

- Using $DOCKER_CONFIG or ~/.docker/config.json
- Proxying and scanning CRI Image Service API
- Using Kubernetes secrets (type = kubernetes.io/dockerconfigjson)

This chart has no place to set authentication. Moreover, is it possible to get secrets dynamically via kubelet client, as our dockerconfigjson is scheduled updated.

2022-12-08 09:27 UTC, merged