fix regex when checking containerd config.toml
dragonflyoss/helm-charts pull request #177
Opened 2023-06-23 03:17 UTC by wyhysj

## Description

There is incorrect regex in dfdaemon-daemonset, when injecting registry auth into containerd config.toml, will generate duplicate entries, which leads to containerd down after changing config.toml

Fix the regex, then should be okay.

2023-07-11 03:33 UTC, gaius-qi commented
@wyhysj 

You should update `Chart.yaml` version:
1. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L6
2. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L7

Add changelog to `Chart.yaml`:
https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L28

2023-07-11 08:13 UTC, wyhysj commented
> @wyhysj
> 
> You should update `Chart.yaml` version:
> 
> 1. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L6
> 2. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L7
> 
> Add changelog to `Chart.yaml`: https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L28

@gaius-qi bumped chart version and added changelog.

2023-07-18 03:23 UTC, gaius-qi requested changes

2023-07-18 03:23 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
> +version: 1.0.4
Update version to `1.0.5`.

2023-07-18 03:23 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
> +appVersion: 1.0.4
Update version to `1.0.5`.

2023-07-18 03:23 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
>      - Update image version to v2.1.0-alpha.6.
Remove previous changelog。

2023-07-18 03:23 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
>      - Add redis configuration in scheduler.
Remove previous changelog。

2023-07-18 03:24 UTC, gaius-qi commented
@wyhysj Please fix request changes. Thanks！

2023-07-18 06:41 UTC, wyhysj commented
> @wyhysj Please fix request changes. Thanks！

@gaius-qi bumped version and removed previous changelog.

2023-07-19 09:15 UTC, merged