Add postgresql database support
dragonflyoss/helm-charts pull request #200
Opened 2023-10-13 09:01 UTC by clcc2019

## Description

## Related Issue

## Motivation and Context

2023-10-16 02:45 UTC, gaius-qi requested changes
@clcc2019 Please add changelog and update chart version, refer to https://github.com/dragonflyoss/helm-charts/pull/190/files.

Helm charts use helm-docs to generate helm documents, refer to https://github.com/dragonflyoss/helm-charts/tree/main/charts.

Remove this.
![image](https://github.com/dragonflyoss/helm-charts/assets/15955374/cc02e92c-313c-4836-a23c-1b476afef09d)

2023-10-18 02:30 UTC, gaius-qi requested changes

2023-10-18 02:30 UTC, gaius-qi commented on charts/dragonfly/values.yaml
> +
Remove blank lines.

2023-10-18 02:32 UTC, gaius-qi commented
@clcc2019 Please rebase main branch.

2023-10-19 02:38 UTC, gaius-qi requested changes
@clcc2019  Remove blank line.

![image](https://github.com/dragonflyoss/helm-charts/assets/15955374/5b80489c-495c-433d-a37a-7968b3369395)

2023-10-19 02:38 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
> +version: 1.2.0
version: 1.1.10

2023-10-19 02:38 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
> +    - Add postgresql database
`- Add postgresql database config.`

2023-10-19 02:38 UTC, gaius-qi commented on charts/dragonfly/Chart.yaml
> +    - Fix dfdaemon seedPeer configmap
`- Fix dfdaemon seedPeer configmap.`

2023-10-20 03:17 UTC, gaius-qi commented
@clcc2019 Please fix lint.

2023-10-22 03:27 UTC, gaius-qi requested changes
Fix lint.

2023-10-31 15:35 UTC, teszes commented
@clcc2019 Are you still working on this? This would be useful to me too, and it seems there is only some lint errors to fix.

2023-11-01 03:39 UTC, clcc2019 commented
> Fix lint.

Can I skip the bitnami charts package check?

2023-11-06 03:48 UTC, gaius-qi commented
> > Fix lint.
> 
> Can I skip the bitnami charts package check?

I don't think it's good.

2023-11-30 10:24 UTC, gaius-qi commented
@clcc2019 Please fix lint.

2024-01-18 02:43 UTC, gaius-qi commented
@clcc2019 Close PR due to no progress for a long time

2024-01-18 02:43 UTC, closed without merging

2024-04-05 02:34 UTC, lucasfcnunes commented
@clcc2019 this PR is a great idea. I am really willing to take over and finish your work.