CDN manager config
dragonflyoss/helm-charts pull request #34
Opened 2021-12-13 04:11 UTC by 244372610

Signed-off-by: 孙伟鹏 <weipeng.swp@alibaba-inc.com>

2021-12-13 05:57 UTC, yxxhero commented on charts/dragonfly/templates/cdn/cdn-configmap.yaml
> +      keepAlive:
keepAlive no value?

2022-01-12 09:37 UTC, gaius-qi requested changes

2022-01-12 09:37 UTC, gaius-qi commented on charts/dragonfly/templates/cdn/cdn-configmap.yaml
> +      keepAlive:
@244372610

2022-01-12 09:46 UTC, gaius-qi requested changes

2022-01-12 09:46 UTC, gaius-qi commented on charts/dragonfly/templates/cdn/cdn-configmap.yaml
> +      keepAlive: { { .Values.cdn.config.base.manager.keepAlive.interval } }
https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/templates/scheduler/scheduler-configmap.yaml#L34

2022-01-12 09:57 UTC, gaius-qi approved these changes
LGTM

2022-01-12 09:58 UTC, merged